# Generated by Django 3.2 on 2021-04-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='def@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(default='pardef@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='teacher_email',
            field=models.EmailField(default='teachdef@gmail.com', max_length=254),
        ),
    ]
