# Generated by Django 3.2 on 2021-04-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_search', '0003_auto_20210411_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
